github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-maintainers"

package:
  repositories:   ["docker.io/paketobuildpacks/syft","gcr.io/paketo-buildpacks/syft"]
  register:       true
  registry_token: ${ secrets.PAKETO_BOT_GITHUB_TOKEN }

docker_credentials:
- registry: gcr.io
  username: _json_key
  password: ${{ secrets.GCR_PUSH_BOT_JSON_KEY }}
- registry: docker.io
  username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
  password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- name:            Syft CLI
  id:              syft
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:       syft_.+_linux_amd64.tar.gz
    owner:      anchore
    repository: syft
    tag_filter: v(0.*)
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}