github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-maintainers"

package:
  repositories:   ["docker.io/paketobuildpacks/syft"]
  register:       true
  registry_token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

docker_credentials:
- registry: docker.io
  username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
  password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- name:            Syft CLI
  id:              syft
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:       syft_.+_linux_amd64.tar.gz
    owner:      anchore
    repository: syft
    tag_filter: v(1.*)
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

# ARM64
- name:            Syft CLI ARM64
  id:              syft
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:       syft_.+_linux_arm64.tar.gz
    owner:      anchore
    repository: syft
    tag_filter: v(1.*)
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    arch:       arm64
