# Copyright 2018-2024 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that contributes the Syft CLI which can be used to generate SBoM information"
  homepage = "https://github.com/paketo-buildpacks/syft"
  id = "paketo-buildpacks/syft"
  keywords = ["bom", "sbom", "bill of materials", "syft"]
  name = "Paketo Buildpack for Syft"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/vnd.syft+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/syft/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/main", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/main", "buildpack.toml"]
  pre-package = "scripts/build.sh"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:anchore:syft:1.48.0:*:*:*:*:*:*:*"]
    id = "syft"
    name = "Syft"
    purl = "pkg:generic/anchore-syft@1.48.0?arch=amd64"
    sha256 = "6cef9a7f37220d9067eaf9cfaaa2fce986e9f320a8d42cbc36658c99af78ea04"
    source = "https://github.com/anchore/syft/archive/refs/tags/v1.48.0.tar.gz"
    source-sha256 = "ee757ade3c9804fde1bdd76474c720d0bb96029df310b12e45d8551545592aa0"
    stacks = ["*"]
    uri = "https://github.com/anchore/syft/releases/download/v1.48.0/syft_1.48.0_linux_amd64.tar.gz"
    version = "1.48.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/anchore/syft/blob/main/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:anchore:syft:1.46.0:*:*:*:*:*:*:*"]
    id = "syft"
    name = "Syft"
    purl = "pkg:generic/anchore-syft@1.46.0?arch=arm64"
    sha256 = "9fafef4db4f032ce81008d3a1529985d41ceb6ccdf2b388c9ce2f1ed7d32082e"
    source = "https://github.com/anchore/syft/archive/refs/tags/v1.46.0.tar.gz"
    source-sha256 = "5545ff8d797fc14d27ae23608ec271609c9038e1732ec13d4ba8042ef542f0ea"
    stacks = ["*"]
    uri = "https://github.com/anchore/syft/releases/download/v1.46.0/syft_1.46.0_linux_arm64.tar.gz"
    version = "1.46.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/anchore/syft/blob/main/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:anchore:syft:1.48.0:*:*:*:*:*:*:*"]
    id = "syft"
    name = "Syft"
    purl = "pkg:generic/anchore-syft@1.48.0?arch=s390x"
    sha256 = "44d33b1cf852719003a6e12bae921c01b36e10376bd44a6ad7fc9ea50e28527b"
    source = "https://github.com/anchore/syft/archive/refs/tags/v1.48.0.tar.gz"
    source-sha256 = "ee757ade3c9804fde1bdd76474c720d0bb96029df310b12e45d8551545592aa0"
    stacks = ["*"]
    uri = "https://github.com/anchore/syft/releases/download/v1.48.0/syft_1.48.0_linux_s390x.tar.gz"
    version = "1.48.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/anchore/syft/blob/main/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:anchore:syft:1.48.0:*:*:*:*:*:*:*"]
    id = "syft"
    name = "Syft"
    purl = "pkg:generic/anchore-syft@1.48.0?arch=ppc64le"
    sha256 = "ab20f136723d08549ed3b887d53a7b086db9cb4ae33fe9ea86624356b3766177"
    source = "https://github.com/anchore/syft/archive/refs/tags/v1.48.0.tar.gz"
    source-sha256 = "ee757ade3c9804fde1bdd76474c720d0bb96029df310b12e45d8551545592aa0"
    stacks = ["*"]
    uri = "https://github.com/anchore/syft/releases/download/v1.48.0/syft_1.48.0_linux_ppc64le.tar.gz"
    version = "1.48.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/anchore/syft/blob/main/LICENSE"

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"

[[targets]]
  arch = "s390x"
  os = "linux"

[[targets]]
  arch = "ppc64le"
  os = "linux"
