api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that contributes the Syft CLI which can be used to generate SBoM information"
  homepage = "https://github.com/paketo-buildpacks/syft"
  id = "paketo-buildpacks/syft"
  keywords = ["bom", "sbom", "bill of materials", "syft"]
  name = "Paketo Buildpack for Syft"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/vnd.syft+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/syft/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run", "linux/ppc64le/bin/build", "linux/ppc64le/bin/detect", "linux/ppc64le/bin/run", "linux/s390x/bin/build", "linux/s390x/bin/detect", "linux/s390x/bin/run"]
  pre-package = "scripts/build.sh --target linux/amd64 --target linux/arm64 --target linux/ppc64le --target linux/s390x"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:54a87372498168b2d033e876fd41fa4e8035b872699e525a57046e1f2f09c860"
    cpe = "cpe:2.3:a:anchore:syft:1.54.0:*:*:*:*:*:*:*"
    id = "syft"
    name = "Syft"
    os = "linux"
    purl = "pkg:generic/anchore-syft@1.54.0?checksum=54a87372498168b2d033e876fd41fa4e8035b872699e525a57046e1f2f09c860&download_url=https://github.com/anchore/syft/releases/download/v1.54.0/syft_1.54.0_linux_amd64.tar.gz"
    source = "https://github.com/anchore/syft/archive/refs/tags/v1.54.0.tar.gz"
    source-checksum = "sha256:bcc7ef841cf0671c46b9c10cb13466a833a5a1dc010c68cc5e3658151c758c2d"
    stacks = ["*"]
    uri = "https://github.com/anchore/syft/releases/download/v1.54.0/syft_1.54.0_linux_amd64.tar.gz"
    version = "1.54.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/anchore/syft/blob/main/LICENSE"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:ee6d4566373a05b344bc6b5f1706f14419bf9338ba39ff686e247deefe9b8818"
    cpe = "cpe:2.3:a:anchore:syft:1.54.0:*:*:*:*:*:*:*"
    id = "syft"
    name = "Syft"
    os = "linux"
    purl = "pkg:generic/anchore-syft@1.54.0?checksum=ee6d4566373a05b344bc6b5f1706f14419bf9338ba39ff686e247deefe9b8818&download_url=https://github.com/anchore/syft/releases/download/v1.54.0/syft_1.54.0_linux_arm64.tar.gz"
    source = "https://github.com/anchore/syft/archive/refs/tags/v1.54.0.tar.gz"
    source-checksum = "sha256:bcc7ef841cf0671c46b9c10cb13466a833a5a1dc010c68cc5e3658151c758c2d"
    stacks = ["*"]
    uri = "https://github.com/anchore/syft/releases/download/v1.54.0/syft_1.54.0_linux_arm64.tar.gz"
    version = "1.54.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/anchore/syft/blob/main/LICENSE"

  [[metadata.dependencies]]
    arch = "s390x"
    checksum = "sha256:270fe7f001d637680f9a9b44d0d73295d68548fd98014ffe0311bc42f5f6afcf"
    cpe = "cpe:2.3:a:anchore:syft:1.54.0:*:*:*:*:*:*:*"
    id = "syft"
    name = "Syft"
    os = "linux"
    purl = "pkg:generic/anchore-syft@1.54.0?checksum=270fe7f001d637680f9a9b44d0d73295d68548fd98014ffe0311bc42f5f6afcf&download_url=https://github.com/anchore/syft/releases/download/v1.54.0/syft_1.54.0_linux_s390x.tar.gz"
    source = "https://github.com/anchore/syft/archive/refs/tags/v1.54.0.tar.gz"
    source-checksum = "sha256:bcc7ef841cf0671c46b9c10cb13466a833a5a1dc010c68cc5e3658151c758c2d"
    stacks = ["*"]
    uri = "https://github.com/anchore/syft/releases/download/v1.54.0/syft_1.54.0_linux_s390x.tar.gz"
    version = "1.54.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/anchore/syft/blob/main/LICENSE"

  [[metadata.dependencies]]
    arch = "ppc64le"
    checksum = "sha256:5c96d7dfa60dc03864ec55ed3fdccf68d1beaf51f281fff91e790769d68a075d"
    cpe = "cpe:2.3:a:anchore:syft:1.54.0:*:*:*:*:*:*:*"
    id = "syft"
    name = "Syft"
    os = "linux"
    purl = "pkg:generic/anchore-syft@1.54.0?checksum=5c96d7dfa60dc03864ec55ed3fdccf68d1beaf51f281fff91e790769d68a075d&download_url=https://github.com/anchore/syft/releases/download/v1.54.0/syft_1.54.0_linux_ppc64le.tar.gz"
    source = "https://github.com/anchore/syft/archive/refs/tags/v1.54.0.tar.gz"
    source-checksum = "sha256:bcc7ef841cf0671c46b9c10cb13466a833a5a1dc010c68cc5e3658151c758c2d"
    stacks = ["*"]
    uri = "https://github.com/anchore/syft/releases/download/v1.54.0/syft_1.54.0_linux_ppc64le.tar.gz"
    version = "1.54.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/anchore/syft/blob/main/LICENSE"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:c069905b391cc4c20a5ba65ad5c10be2a7ba074f8ea6ad203e24d14e303dad47"
    cpe = "cpe:2.3:a:anchore:syft:1.54.1:*:*:*:*:*:*:*"
    id = "syft"
    name = "Syft"
    os = "linux"
    purl = "pkg:generic/anchore-syft@1.54.1?checksum=c069905b391cc4c20a5ba65ad5c10be2a7ba074f8ea6ad203e24d14e303dad47&download_url=https://github.com/anchore/syft/releases/download/v1.54.1/syft_1.54.1_linux_amd64.tar.gz"
    source = "https://github.com/anchore/syft/archive/refs/tags/v1.54.1.tar.gz"
    source-checksum = "sha256:e3a8b41ef4050665edb7cb35bea1ffe49ab7bbdd3127e756ea7cf979d41e9dd5"
    stacks = ["*"]
    uri = "https://github.com/anchore/syft/releases/download/v1.54.1/syft_1.54.1_linux_amd64.tar.gz"
    version = "1.54.1"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/anchore/syft/blob/main/LICENSE"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:dfdf0537610113edbefe1f1fc6548bc957b2d77439636ec824fcf0e10d46d054"
    cpe = "cpe:2.3:a:anchore:syft:1.54.1:*:*:*:*:*:*:*"
    id = "syft"
    name = "Syft"
    os = "linux"
    purl = "pkg:generic/anchore-syft@1.54.1?checksum=dfdf0537610113edbefe1f1fc6548bc957b2d77439636ec824fcf0e10d46d054&download_url=https://github.com/anchore/syft/releases/download/v1.54.1/syft_1.54.1_linux_arm64.tar.gz"
    source = "https://github.com/anchore/syft/archive/refs/tags/v1.54.1.tar.gz"
    source-checksum = "sha256:e3a8b41ef4050665edb7cb35bea1ffe49ab7bbdd3127e756ea7cf979d41e9dd5"
    stacks = ["*"]
    uri = "https://github.com/anchore/syft/releases/download/v1.54.1/syft_1.54.1_linux_arm64.tar.gz"
    version = "1.54.1"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/anchore/syft/blob/main/LICENSE"

  [[metadata.dependencies]]
    arch = "s390x"
    checksum = "sha256:d974dea5baa7066d89dd87ce333d156a20a500193b3bafe1ae5a576573bcc4ce"
    cpe = "cpe:2.3:a:anchore:syft:1.54.1:*:*:*:*:*:*:*"
    id = "syft"
    name = "Syft"
    os = "linux"
    purl = "pkg:generic/anchore-syft@1.54.1?checksum=d974dea5baa7066d89dd87ce333d156a20a500193b3bafe1ae5a576573bcc4ce&download_url=https://github.com/anchore/syft/releases/download/v1.54.1/syft_1.54.1_linux_s390x.tar.gz"
    source = "https://github.com/anchore/syft/archive/refs/tags/v1.54.1.tar.gz"
    source-checksum = "sha256:e3a8b41ef4050665edb7cb35bea1ffe49ab7bbdd3127e756ea7cf979d41e9dd5"
    stacks = ["*"]
    uri = "https://github.com/anchore/syft/releases/download/v1.54.1/syft_1.54.1_linux_s390x.tar.gz"
    version = "1.54.1"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/anchore/syft/blob/main/LICENSE"

  [[metadata.dependencies]]
    arch = "ppc64le"
    checksum = "sha256:0b86f1ccb39675d9376ba48cc92eb369a020a6ed28c1dc80e02d08ef9cdf3f66"
    cpe = "cpe:2.3:a:anchore:syft:1.54.1:*:*:*:*:*:*:*"
    id = "syft"
    name = "Syft"
    os = "linux"
    purl = "pkg:generic/anchore-syft@1.54.1?checksum=0b86f1ccb39675d9376ba48cc92eb369a020a6ed28c1dc80e02d08ef9cdf3f66&download_url=https://github.com/anchore/syft/releases/download/v1.54.1/syft_1.54.1_linux_ppc64le.tar.gz"
    source = "https://github.com/anchore/syft/archive/refs/tags/v1.54.1.tar.gz"
    source-checksum = "sha256:e3a8b41ef4050665edb7cb35bea1ffe49ab7bbdd3127e756ea7cf979d41e9dd5"
    stacks = ["*"]
    uri = "https://github.com/anchore/syft/releases/download/v1.54.1/syft_1.54.1_linux_ppc64le.tar.gz"
    version = "1.54.1"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/anchore/syft/blob/main/LICENSE"

  [[metadata.dependency-constraints]]
    constraint = "1.*"
    id = "syft"
    patches = 2

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"

[[targets]]
  arch = "s390x"
  os = "linux"

[[targets]]
  arch = "ppc64le"
  os = "linux"
