api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that contributes the Syft CLI which can be used to generate SBoM information"
  homepage = "https://github.com/paketo-buildpacks/syft"
  id = "paketo-buildpacks/syft"
  keywords = ["bom", "sbom", "bill of materials", "syft"]
  name = "Paketo Buildpack for Syft"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/vnd.syft+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/syft/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run", "linux/ppc64le/bin/build", "linux/ppc64le/bin/detect", "linux/ppc64le/bin/run", "linux/s390x/bin/build", "linux/s390x/bin/detect", "linux/s390x/bin/run"]
  pre-package = "scripts/build.sh --target linux/amd64 --target linux/arm64 --target linux/ppc64le --target linux/s390x"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:caeedb81fb0491615f1ebd1761e4145d41ee86dd2cc7bf80669f9f5ad9d6133d"
    cpe = "cpe:2.3:a:anchore:syft:1.52.0:*:*:*:*:*:*:*"
    id = "syft"
    name = "Syft"
    os = "linux"
    purl = "pkg:generic/anchore-syft@1.52.0?checksum=caeedb81fb0491615f1ebd1761e4145d41ee86dd2cc7bf80669f9f5ad9d6133d&download_url=https://github.com/anchore/syft/releases/download/v1.52.0/syft_1.52.0_linux_amd64.tar.gz"
    source = "https://github.com/anchore/syft/archive/refs/tags/v1.52.0.tar.gz"
    source-checksum = "sha256:8b999a1b8bd08b12512176cdec5d063db9cfe209c65cc5de9c4eb2ab7bdc7b3c"
    stacks = ["*"]
    uri = "https://github.com/anchore/syft/releases/download/v1.52.0/syft_1.52.0_linux_amd64.tar.gz"
    version = "1.52.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/anchore/syft/blob/main/LICENSE"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:c46d5e4c28e12aa4c5becfaa343ef1c7f89045b6b895f2c21d471c62db09c706"
    cpe = "cpe:2.3:a:anchore:syft:1.52.0:*:*:*:*:*:*:*"
    id = "syft"
    name = "Syft"
    os = "linux"
    purl = "pkg:generic/anchore-syft@1.52.0?checksum=c46d5e4c28e12aa4c5becfaa343ef1c7f89045b6b895f2c21d471c62db09c706&download_url=https://github.com/anchore/syft/releases/download/v1.52.0/syft_1.52.0_linux_arm64.tar.gz"
    source = "https://github.com/anchore/syft/archive/refs/tags/v1.52.0.tar.gz"
    source-checksum = "sha256:8b999a1b8bd08b12512176cdec5d063db9cfe209c65cc5de9c4eb2ab7bdc7b3c"
    stacks = ["*"]
    uri = "https://github.com/anchore/syft/releases/download/v1.52.0/syft_1.52.0_linux_arm64.tar.gz"
    version = "1.52.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/anchore/syft/blob/main/LICENSE"

  [[metadata.dependencies]]
    arch = "s390x"
    checksum = "sha256:3390332ebcd56c20541a95f5531565cf049022344cef60b945b34680a1955b2f"
    cpe = "cpe:2.3:a:anchore:syft:1.52.0:*:*:*:*:*:*:*"
    id = "syft"
    name = "Syft"
    os = "linux"
    purl = "pkg:generic/anchore-syft@1.52.0?checksum=3390332ebcd56c20541a95f5531565cf049022344cef60b945b34680a1955b2f&download_url=https://github.com/anchore/syft/releases/download/v1.52.0/syft_1.52.0_linux_s390x.tar.gz"
    source = "https://github.com/anchore/syft/archive/refs/tags/v1.52.0.tar.gz"
    source-checksum = "sha256:8b999a1b8bd08b12512176cdec5d063db9cfe209c65cc5de9c4eb2ab7bdc7b3c"
    stacks = ["*"]
    uri = "https://github.com/anchore/syft/releases/download/v1.52.0/syft_1.52.0_linux_s390x.tar.gz"
    version = "1.52.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/anchore/syft/blob/main/LICENSE"

  [[metadata.dependencies]]
    arch = "ppc64le"
    checksum = "sha256:6b35bb39a87582eb4a4c27e3d3c92f26725f21fc6b309cd85a3aa7af5ccb492e"
    cpe = "cpe:2.3:a:anchore:syft:1.52.0:*:*:*:*:*:*:*"
    id = "syft"
    name = "Syft"
    os = "linux"
    purl = "pkg:generic/anchore-syft@1.52.0?checksum=6b35bb39a87582eb4a4c27e3d3c92f26725f21fc6b309cd85a3aa7af5ccb492e&download_url=https://github.com/anchore/syft/releases/download/v1.52.0/syft_1.52.0_linux_ppc64le.tar.gz"
    source = "https://github.com/anchore/syft/archive/refs/tags/v1.52.0.tar.gz"
    source-checksum = "sha256:8b999a1b8bd08b12512176cdec5d063db9cfe209c65cc5de9c4eb2ab7bdc7b3c"
    stacks = ["*"]
    uri = "https://github.com/anchore/syft/releases/download/v1.52.0/syft_1.52.0_linux_ppc64le.tar.gz"
    version = "1.52.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/anchore/syft/blob/main/LICENSE"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:54a87372498168b2d033e876fd41fa4e8035b872699e525a57046e1f2f09c860"
    cpe = "cpe:2.3:a:anchore:syft:1.54.0:*:*:*:*:*:*:*"
    id = "syft"
    name = "Syft"
    os = "linux"
    purl = "pkg:generic/anchore-syft@1.54.0?checksum=54a87372498168b2d033e876fd41fa4e8035b872699e525a57046e1f2f09c860&download_url=https://github.com/anchore/syft/releases/download/v1.54.0/syft_1.54.0_linux_amd64.tar.gz"
    source = "https://github.com/anchore/syft/archive/refs/tags/v1.54.0.tar.gz"
    source-checksum = "sha256:bcc7ef841cf0671c46b9c10cb13466a833a5a1dc010c68cc5e3658151c758c2d"
    stacks = ["*"]
    uri = "https://github.com/anchore/syft/releases/download/v1.54.0/syft_1.54.0_linux_amd64.tar.gz"
    version = "1.54.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/anchore/syft/blob/main/LICENSE"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:ee6d4566373a05b344bc6b5f1706f14419bf9338ba39ff686e247deefe9b8818"
    cpe = "cpe:2.3:a:anchore:syft:1.54.0:*:*:*:*:*:*:*"
    id = "syft"
    name = "Syft"
    os = "linux"
    purl = "pkg:generic/anchore-syft@1.54.0?checksum=ee6d4566373a05b344bc6b5f1706f14419bf9338ba39ff686e247deefe9b8818&download_url=https://github.com/anchore/syft/releases/download/v1.54.0/syft_1.54.0_linux_arm64.tar.gz"
    source = "https://github.com/anchore/syft/archive/refs/tags/v1.54.0.tar.gz"
    source-checksum = "sha256:bcc7ef841cf0671c46b9c10cb13466a833a5a1dc010c68cc5e3658151c758c2d"
    stacks = ["*"]
    uri = "https://github.com/anchore/syft/releases/download/v1.54.0/syft_1.54.0_linux_arm64.tar.gz"
    version = "1.54.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/anchore/syft/blob/main/LICENSE"

  [[metadata.dependencies]]
    arch = "s390x"
    checksum = "sha256:270fe7f001d637680f9a9b44d0d73295d68548fd98014ffe0311bc42f5f6afcf"
    cpe = "cpe:2.3:a:anchore:syft:1.54.0:*:*:*:*:*:*:*"
    id = "syft"
    name = "Syft"
    os = "linux"
    purl = "pkg:generic/anchore-syft@1.54.0?checksum=270fe7f001d637680f9a9b44d0d73295d68548fd98014ffe0311bc42f5f6afcf&download_url=https://github.com/anchore/syft/releases/download/v1.54.0/syft_1.54.0_linux_s390x.tar.gz"
    source = "https://github.com/anchore/syft/archive/refs/tags/v1.54.0.tar.gz"
    source-checksum = "sha256:bcc7ef841cf0671c46b9c10cb13466a833a5a1dc010c68cc5e3658151c758c2d"
    stacks = ["*"]
    uri = "https://github.com/anchore/syft/releases/download/v1.54.0/syft_1.54.0_linux_s390x.tar.gz"
    version = "1.54.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/anchore/syft/blob/main/LICENSE"

  [[metadata.dependencies]]
    arch = "ppc64le"
    checksum = "sha256:5c96d7dfa60dc03864ec55ed3fdccf68d1beaf51f281fff91e790769d68a075d"
    cpe = "cpe:2.3:a:anchore:syft:1.54.0:*:*:*:*:*:*:*"
    id = "syft"
    name = "Syft"
    os = "linux"
    purl = "pkg:generic/anchore-syft@1.54.0?checksum=5c96d7dfa60dc03864ec55ed3fdccf68d1beaf51f281fff91e790769d68a075d&download_url=https://github.com/anchore/syft/releases/download/v1.54.0/syft_1.54.0_linux_ppc64le.tar.gz"
    source = "https://github.com/anchore/syft/archive/refs/tags/v1.54.0.tar.gz"
    source-checksum = "sha256:bcc7ef841cf0671c46b9c10cb13466a833a5a1dc010c68cc5e3658151c758c2d"
    stacks = ["*"]
    uri = "https://github.com/anchore/syft/releases/download/v1.54.0/syft_1.54.0_linux_ppc64le.tar.gz"
    version = "1.54.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/anchore/syft/blob/main/LICENSE"

  [[metadata.dependency-constraints]]
    constraint = "1.*"
    id = "syft"
    patches = 2

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"

[[targets]]
  arch = "s390x"
  os = "linux"

[[targets]]
  arch = "ppc64le"
  os = "linux"
